# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb56fb5405ffbc7c8b3a4ff5d521ef990f1b5705678e14330e6df03340abdb17fe13e222d031e9587344e8595aa80379fe90f4b6e64ed4101a106250db82f09d

test:
  secret_key_base: c968b817dd99b34de8295c73a15a46afe91775ccc634118cba9e7d8025d5482ccc57a2ccd47864fee2e727b2fb9bcbce060c4e670c00fa891961f636b3e5fa99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
